-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bmaze.Object.Book exposing (..)

import Bmaze.InputObject
import Bmaze.Interface
import Bmaze.Object
import Bmaze.Scalar
import Bmaze.ScalarCodecs
import Bmaze.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


author : SelectionSet (Maybe String) Bmaze.Object.Book
author =
    Object.selectionForField "(Maybe String)" "author" [] (Decode.string |> Decode.nullable)


code : SelectionSet Bmaze.ScalarCodecs.Id Bmaze.Object.Book
code =
    Object.selectionForField "ScalarCodecs.Id" "code" [] (Bmaze.ScalarCodecs.codecs |> Bmaze.Scalar.unwrapCodecs |> .codecId |> .decoder)


date : SelectionSet (Maybe String) Bmaze.Object.Book
date =
    Object.selectionForField "(Maybe String)" "date" [] (Decode.string |> Decode.nullable)


lead : SelectionSet (Maybe String) Bmaze.Object.Book
lead =
    Object.selectionForField "(Maybe String)" "lead" [] (Decode.string |> Decode.nullable)


title : SelectionSet String Bmaze.Object.Book
title =
    Object.selectionForField "String" "title" [] Decode.string
