-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bmaze.Object.Scene exposing (..)

import Bmaze.InputObject
import Bmaze.Interface
import Bmaze.Object
import Bmaze.Scalar
import Bmaze.ScalarCodecs
import Bmaze.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


body : SelectionSet String Bmaze.Object.Scene
body =
    Object.selectionForField "String" "body" [] Decode.string


bodyHtml : SelectionSet String Bmaze.Object.Scene
bodyHtml =
    Object.selectionForField "String" "bodyHtml" [] Decode.string


choices :
    SelectionSet decodesTo Bmaze.Object.Choice
    -> SelectionSet (Maybe (List decodesTo)) Bmaze.Object.Scene
choices object____ =
    Object.selectionForCompositeField "choices" [] object____ (identity >> Decode.list >> Decode.nullable)


code : SelectionSet Bmaze.ScalarCodecs.Id Bmaze.Object.Scene
code =
    Object.selectionForField "ScalarCodecs.Id" "code" [] (Bmaze.ScalarCodecs.codecs |> Bmaze.Scalar.unwrapCodecs |> .codecId |> .decoder)


image : SelectionSet Bool Bmaze.Object.Scene
image =
    Object.selectionForField "Bool" "image" [] Decode.bool


sceneno : SelectionSet Int Bmaze.Object.Scene
sceneno =
    Object.selectionForField "Int" "sceneno" [] Decode.int


title : SelectionSet (Maybe String) Bmaze.Object.Scene
title =
    Object.selectionForField "(Maybe String)" "title" [] (Decode.string |> Decode.nullable)
