-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bmaze.Mutation exposing (..)

import Bmaze.InputObject
import Bmaze.Interface
import Bmaze.Object
import Bmaze.Scalar
import Bmaze.ScalarCodecs
import Bmaze.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias DeleteBookRequiredArguments =
    { code : Bmaze.ScalarCodecs.Id }


{-| delete book
-}
deleteBook :
    DeleteBookRequiredArguments
    -> SelectionSet decodesTo Bmaze.Object.DeleteBookPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
deleteBook requiredArgs____ object____ =
    Object.selectionForCompositeField "deleteBook" [ Argument.required "code" requiredArgs____.code (Bmaze.ScalarCodecs.codecs |> Bmaze.Scalar.unwrapEncoder .codecId) ] object____ (identity >> Decode.nullable)


type alias UpdateBookOptionalArguments =
    { author : OptionalArgument String
    , date : OptionalArgument String
    , lead : OptionalArgument String
    }


type alias UpdateBookRequiredArguments =
    { code : Bmaze.ScalarCodecs.Id
    , title : String
    }


{-| update book
-}
updateBook :
    (UpdateBookOptionalArguments -> UpdateBookOptionalArguments)
    -> UpdateBookRequiredArguments
    -> SelectionSet decodesTo Bmaze.Object.UpdateBookPayload
    -> SelectionSet (Maybe decodesTo) RootMutation
updateBook fillInOptionals____ requiredArgs____ object____ =
    let
        filledInOptionals____ =
            fillInOptionals____ { author = Absent, date = Absent, lead = Absent }

        optionalArgs____ =
            [ Argument.optional "author" filledInOptionals____.author Encode.string, Argument.optional "date" filledInOptionals____.date Encode.string, Argument.optional "lead" filledInOptionals____.lead Encode.string ]
                |> List.filterMap identity
    in
    Object.selectionForCompositeField "updateBook" (optionalArgs____ ++ [ Argument.required "code" requiredArgs____.code (Bmaze.ScalarCodecs.codecs |> Bmaze.Scalar.unwrapEncoder .codecId), Argument.required "title" requiredArgs____.title Encode.string ]) object____ (identity >> Decode.nullable)
