-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Bmaze.Object exposing (..)


type Book
    = Book


type Choice
    = Choice


type DeleteBookPayload
    = DeleteBookPayload


type Scene
    = Scene


type UpdateBookPayload
    = UpdateBookPayload
